
[project]
name = "src"
version = "0.0.1"
description = "An MLOps project for learning "
authors = [{name = "Avez Mulani", email = "avezmulani786@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
